import type { Metadata } from 'next'
import { Open_Sans, Quicksand } from 'next/font/google'

import './globals.css'
import Providers from './providers'
import Navbar from '@/components/Navbar'

const quickSand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quickSand',
  preload: true,
})
const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-openSans',
  preload: true,
})

export const metadata: Metadata = {
  title: 'DyArdh | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ colorScheme: 'dark' }} suppressHydrationWarning>
      <body
        className={`${quickSand.variable} ${openSans.variable} font-openSans no-scrollbar`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
